### ISSUE TITLE
Feature: Allow preferring to sort in descending order

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-table#208]
## What
If a column is sortable, but initially unsorted, clicking the heading once sorts in ascending order, clicking again goes to descending. 

It would be great to be able to specify that if the user chooses to sort, prefer to put in descending order on the first click. Use case: on https://risks.in.ft.com/, for any sortable column it makes sense to sort with the largest, scariest values at the top.

I have no thoughts about what the API should be, other than a declarative way of doing it would be good (maybe it already exists but I've been unable to find it?).

**Comment by notlee** [comment]
There's no way to do this at the moment without sorting the table with the `sortRowsByColumn(columnIndex, sortOrder)` method. Adding a constructor option with declarative attribute like `o-table-initial-sort-order` seems like a good new feature to me :)

**Comment by wheresrhys** [comment]
Thanks for the new feature - we will use it as soon as we can get a build out.

But we also have a use case fro applying different settings per column:
- the name field should be sorted ascending
- the score field should be sorted descending

**Comment by notlee** [comment]
hey I asked for design input on this in the [design-ops channel](https://financialtimes.slack.com/archives/C01481FKWA2/p1606908299168600). Josh replied with some thoughts:

>Starting with descending on first click
>^ I think this is pretty low risk, and has a good rationale behind it.

>Having each column individually sort differently
>^ I would keep it the same for all, customisable to either starting with ascending or descending. But not different behaviour for each - as you may increase the cognitive load on the user if the expected behaviour suddenly changes from one column to the next.

I'm glad we're agreed on choosing the default table sort across all columns, since we implemented that already! 😅 I agree having a different default sort per column has problems and is not intuitive. We need to find another way to solve your problem. Was the goal to show high risk rows as a priority? Instead of defaulting the sort order on click differently to other rows one approach could be to sort server the data side so the highest risk is shown immediately without further user interaction. At a glance it looks like the risk register is actually already doing that now, so I'm going to close this issue. But let me know if you'd like to discuss this or a similar UX question with the design team. Sorry this issue sat around after the initial work

**Comment by wheresrhys** [comment]
I disagree quite strongly.

I think the issue here is that for different data types, custom sort order per column absolutely makes sense, and can make tables more intuitive, while I think the argument put forward above only really applies to columns of the same data type as each other.

> one approach could be to sort the data server side so the highest risk is shown immediately without further user interaction

We already do this, but the decision above means that if a user sorts by another column, and then clicks back to sort on the score column it will be in the opposite order to the original view. Again, quite unintuitive I would say.

**Comment by notlee** [comment]
>We already do this, but the decision above means that if a user sorts by another column, and then clicks back to sort on the score column it will be in the opposite order to the original view. Again, quite unintuitive I would say.

That's not the case with `data-o-table-preferred-sort-order="descending"`, to prioritise score as a sortable column.

>I think the issue here is that for different data types, custom sort order per column absolutely makes sense, and can make tables more intuitive, while I think the argument put forward above only really applies to columns of the same data type as each other.

Maybe. [This blog advocates that approach](https://blog.jooq.org/2016/03/07/ui-developers-choose-sensible-default-ordering/) but otherwise I've never seen a sortable table that behaves that way. The pattern of clicking a table column twice to toggle sort is a pretty established, if imperfect, pattern around the web and in that way is reasonably intuitive. Allowing each columns sort order to be configured individually breaks that pre-built expectation. It breaks down further if the user has a goal in mind the product owners didn't originally expect. 

The guidance so far is to stick with the established pattern even if it requires an extra click in this usecase. I'll reopen the issue though to confirm with a broader group of the design team in the weekly design ops meeting. Would you like to come along to that?

**Comment by wheresrhys** [comment]
> data-o-table-preferred-sort-order="descending"

But if I set that globally then alphabetical sort is descending too, which is not what I, or the user, will expect when clicking a column to sort alphabetically.

> breaks that pre-built expectation

I think this is an imagined breaking of expectations based on a hypothetical example where every column is sorted differently, even when they have the same data type. I am after something far more restrained and less expectation breaking: I want the number columns to sort descending when clicked once, but the text columns to sort alphabetically ascending. Arguing that I have to make one decision feels like unnecessary inflexibility to guard against a hypothetical scenario when a developer might go wild and add all sorts of random sort orders. As I said - I think that's quite pessimistic. 

>  I've never seen a sortable table that behaves that way

Maybe you have, but haven't noticed because the developer has chosen the most intuitive ordering, able to do so per column when necessary?

**Comment by notlee** [comment]
>Maybe you have, but haven't noticed because the developer has chosen the most intuitive ordering, able to do so per column when necessary?

No I looked at GDS, Material UI, Carbon Design, Lightning to see how their tables worked. I'm not 100% but couldn't find existing examples from these large design systems. That's not to say we shouldn't but points to this being niche and potentially not an intuitive pattern.

>I want the number columns to sort descending when clicked once, but the text columns to sort alphabetically ascending.

That expectation is not based on data type but use-case, the data that the user wants to see in that moment. Depending on the number the user might want to see high or low values. A product owner could pre-empt that and configure the table accordingly but again table sort being context dependent and changing per page and per column doesn't feel helpful.

Ultimately I'd defer to a designer on this. Would you like to come along to the design ops meeting to discuss the problem you're trying to solve?

**Comment by chee** [comment]
i've posted the link to this issue in the #design-ops channel on Slack.
i'm going to close it because it appears a design decision was already made not to go forward with this request.
feel free to continue the discussion here, or in the #design-ops channel.
