### ISSUE TITLE
Should striped tables take hidden elements into account?

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/o-table#29]
Hey,

I've a use-case now where we're hiding elements in a table using an absurdly simplistic search, which involves setting the display of rows to none.  This works fairly well, however using a striped o-table I get this:
![Borked](http://d.ax.gy/RYSI+)

Any ideas on how to best address this?

**Comment by onishiweb** [comment]
Hi @antoligy, thanks for the issue. I've looked into it and been thinking about a possible solution but I can't come up with any that wouldn't require us manipulating the table with JavaScript in the component. Which I don't think is a great solution for something like striped rows...

The rows are striped using the `nth-child(even)` selector, which takes into account all children of the element regardless of the display property. Hence why you're seeing the dodgy striping. I'm not sure it'll be possible in your situation but instead of hiding the rows, would you be able to store a copy of the full table and remove the rows entirely, that would allow for the `nth-child` selector to work in this case?
